services:
  - type: web
    name: portfolio
    plan: free
    buildCommand: composer install --no-dev --optimize-autoloader && npm install && npm run build && php artisan config:cache && php artisan route:cache && php artisan view:cache
    startCommand: php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_NAME
        value: DeveloperPortfolio
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:25gK8U3Z0FUIYmK7tIPWKlgJzLVBnr/7GvqVhU63nU8=
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        sync: false
      - key: DB_CONNECTION
        value: sqlite
      - key: SESSION_DRIVER
        value: file
      - key: LOG_CHANNEL
        value: stack
